DFXML_WRITER = dfxml/src/dfxml_writer.cpp \
      dfxml/src/dfxml_writer.h \
      dfxml/src/hash_t.h 

DFXML_READER = dfxml/src/dfxml_reader.cpp \
      dfxml/src/dfxml_reader.h \
      dfxml/src/hash_t.h 
